# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d22e372ba076879375da9200484d9116c29f8516f7823a220dd102a3fcc4f3750dec3c1a0003f3caaf3ee687f2babd82d94515c572b1b7f0689b72ecb493dff6

test:
  secret_key_base: 455c3091ccaade4ebd2aafd07466ffcd168102a2ce9d6ae44d58bec6e560412825989b520735ccc7ce0b84e680639dc1b94f7e5a3213b0622f7e5fd7936d978a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
